### ISSUE TITLE
Cloded by inactivity

### ISSUE THREAD

**Issue by nicolasmacia** [CERTUNLP/NgenBundle#106]
A partir de la ultima version de NGEN, no se están cerrando por inactividad los incidentes de manera automatica. 
Esto es comprensible puesto que no todos los incidentes son iguales. Debería poder configurarse cuales tipos de incidentes se cierran automaticamente de esta manera. Por ejemplo los que un feed informa y de un dia para otro deja de informar.

**Comment by einar-lanfranco** [comment]
Esta resuelto:
La decision de que incidente se cierra y cual no depende del incidente en si, inicialmente viene de la decision y los tiempos para calcular eso provienen de las prioridades
