### ISSUE TITLE
Decisiones por defecto

### ISSUE THREAD

**Issue by nicolasmacia** [CERTUNLP/NgenBundle#121]
Dado que los feeds reportan distintos tipos de cosas de distintas organizaciones, estaría bueno manejar con las decisiones las cosas que se quieren incorporar al sistema y cuales no.

Por ejemplo, estaría bueno indicar que si algo no va a nuestra comunidad objetivo, entonces ignorarlo.

**Comment by einar-lanfranco** [comment]
La decision filtra por tipo, feed y red. Filtras la decisión por RED y listo.
