### ISSUE TITLE
Error en la busqueda de prioidad en el formulario de Inicdent

### ISSUE THREAD

**Issue by einar-lanfranco** [CERTUNLP/NgenBundle#128]
Busca por id y le manda  el slug.

Se carga el tipo por ejemplo -> eso busca la decision-> la decision trae impato y urgencia-> con esos dos se forma el slug, pero el llamado que  se hace es con el slug cuando la api espera el id, entonces siempre falla.
La llamada esta en IncidentApi,js function searchPriority

**Comment by rubiodamian** [comment]
la decision deberia tener deberia tener la prioridad y no el impacto y urgencia. 
Impacto y urgencia es para el front para poder decidir cual prioridad va.
