### ISSUE TITLE
Error en el activar o desactivar tipos desde el listado

### ISSUE THREAD

**Issue by einar-lanfranco** [CERTUNLP/NgenBundle#131]
No funciona ni con acciones ni con el boton nuevo

**Comment by rubiodamian** [comment]
si esto habla de /administration/types/ . Lo probe en dev y prod y andan.

**Comment by einar-lanfranco** [comment]
El problema pasa solo con la primera vez q tocas en el listado 2020-03-10 12:17:20] request.CRITICAL: Uncaught PHP Exception Elastica\Exception\Bulk\ResponseException: "Error in one or more bulk request actions:  update: /types_prod/type/bluekeep caused object mapping for [reports] tried to parse field [null] as object, but found a concrete value " at /application/ngen_basic/vendor/ruflin/elastica/lib/Elastica/Bulk.php line 410 {"exception":"[object] (Elastica\\Exception\\Bulk\\ResponseException(code: 0): Error in one or more bulk request actions:\n\nupdate: /types_prod/type/bluekeep caused object mapping for [reports] tried to parse field [null] as object, but found a concrete value\n at /application/ngen_basic/vendor/ruflin/elastica/lib/Elastica/Bulk.php:410)"} []

Entras en http://localhost:8000/administration/types/ y si tocas Change se rompe da 500
