### ISSUE TITLE
Funcionalidad nueva para la API - Información de un host

### ISSUE THREAD

**Issue by matiferrigno** [CERTUNLP/NgenBundle#19]
Estaría bueno (a menos a mí me serviría) que a la API se le pueda consultar por un host (X.X.X.X) 
y retorne información útil.  Ejemplos serían, su red, la descripción de la unidad académica a la que pertenece y quién es su administrador responsable. ¿Es viable?

**Comment by rubiodamian** [comment]
ahora se puede consultar esta info en /api/v1/networks/host/192.168.1.10
