### ISSUE TITLE
Separar los plugins en un  bundle aparte

### ISSUE THREAD

**Issue by rubiodamian** [CERTUNLP/NgenBundle#34]
Tenemos muchos scripts y plugins que están por todos lados. Podemos englobarlo todo en un bundle nuevo y generar una configuración acorde que se agregue a la configuración de Ngen.

**Comment by mateodurante** [comment]
Podría existir **FeedsBundle** que levante por composer los repositorios de cada feed y disponga de una interfaz para:
- Activarlos/desactivarlos por separado.
- Configurar el Cron para cada uno.
- Disponer de una interfaz web para cambiar la configuración de cada uno, para esto hay que establecer una forma de compartir esta configuración con los scripts, ya sea reescribiendo el archivo de configuración propio del script, enviándole por parámetro al momento de ser ejecutado u otro medio para compartir la información de configuración.

**Comment by rubiodamian** [comment]
https://github.com/egzakt/UnifikDatabaseConfigBundle
podriamos utilizar esto para leventar la config en la base de datos. Tambien seria optimo cifrar en la base de datos la config

**Comment by mateodurante** [comment]
Agregando, para aproximar a la finalidad y modularidad:
- Las configuraciones de los feeds debieran estar cifradas en la base de datos, Ngen desifra la configuración de cada feed y se la envía al momento de ejecutar por la entrada estandar.
- Todos los feeds deberán tener un .sh para correr el mismo.
- Los feeds devolverán un json con todos los incidentes a reportar. Será el bundle de feeds quien se encargue de cargar estos incidentes y reportar errores en caso de ocurrir.
