### ISSUE TITLE
Organización del formulario de nuevo incidente 

### ISSUE THREAD

**Issue by mateodurante** [CERTUNLP/NgenBundle#36]
Estaria bueno que el orden de los campos sea de acuerdo a lo que falta completar y lo que viene completado por defecto, o sea, poner Date, State y Edit report al final del formulario.

Además estaría bueno que la evidencia pueda ser tanto un archivo que se suba como ahora o como un textarea donde pegar el texto de la evidencia directamente sin necesidad de subir un archivo.

![image](https://user-images.githubusercontent.com/668847/40378357-afd7cace-5dc9-11e8-95d0-22bc73658193.png)

**Comment by einar-lanfranco** [comment]
Así va bien?



![mateo](https://user-images.githubusercontent.com/3857748/47828279-22c98b00-dd61-11e8-8a1f-55aed601a365.png)
