### ISSUE TITLE
Soporte de reverse proxy

### ISSUE THREAD

**Issue by asabolansky** [CERTUNLP/NgenBundle#50]
Hay links, como el de activación que llega por mail que viene con http. Dar soporte a reverse_proxy con algún tipo de variable que si está en true arme los links con https.

**Comment by einar-lanfranco** [comment]
Resuelto, para Docker ya estaría, con el dockercomposenew.yml de la carpeta Docker debería estar solucionado, si necesitas instalarlo a mano tenes que pasar los parametros al nginx 

  proxy_redirect     off;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Host $server_name;
      proxy_set_header        X-Forwarded-Port   $server_port;
      proxy_set_header        X-Forwarded-Proto  $scheme;

y tocar el ....web/app.php incluyendo la línea  

Request::setTrustedProxies(array('127.0.0.1', $request->server->get('REMOTE_ADDR')));

o podés tocar la configuración de la app, según explican en https://symfony.com/doc/2.8/deployment/proxies.html.
