### ISSUE TITLE
Enriquecimiento (Country y ASN)

### ISSUE THREAD

**Issue by nicolasmacia** [CERTUNLP/NgenBundle#66]
A partir de una IP, es posible registrar el Pais y el ASN utilizando un servicio como el de Team Cymru:

$ whois -h whois.cymru.com 163.10.5.66
AS      | IP               | AS Name
5692    | 163.10.5.66      | Universidad Nacional de La Plata, AR

Referencia: http://www.team-cymru.com/IP-ASN-mapping.html#whois

**Comment by rubiodamian** [comment]
solved in c686d11ec6fce02b9b41cd45991c19534adab353
