### ISSUE TITLE
Separator in add decision

### ISSUE THREAD

**Issue by puckk** [CERTUNLP/NgenBundle#80]
![image](https://user-images.githubusercontent.com/18028177/55097872-800d0280-509b-11e9-89ed-6c227ac292e1.png)

Debería haber un separador entre Tipo/Feed/Red y el resto de los campos (Una cosa es condición y la otra la acción)

**Comment by einar-lanfranco** [comment]
![Captura de pantalla de 2019-04-01 19-13-00](https://user-images.githubusercontent.com/3857748/55363105-6102dc00-54b2-11e9-8814-3e5719ee218d.png)

Asi esta bien?

**Comment by puckk** [comment]
(Y)
