### ISSUE TITLE
CSRF y no apikey

### ISSUE THREAD

**Issue by puckk** [CERTUNLP/NgenBundle#81]
Todas las acciones deberían tener token csrf, y NO mandar la apikey por la URL (GET)

**Comment by einar-lanfranco** [comment]
El orden en que busca es header, request, query, es decir si lo mandas por el header se soluciona.

Para rest como es sin estado no deberias tener que preocuparte por csrf, si te roban la apikey ya estas comprometido. Me hiciste dudar asi qeu fui a las fuentes https://security.stackexchange.com/questions/166724/should-i-use-csrf-protection-on-rest-api-endpoints

Si es algo a reportar si ocurre lo mismo por el frontend
